export const CONFIG = {
  DB_NAME: "YouTubeTranscriptPro",
  DB_VERSION: 2,
  STORE_NAME: "transcripts",
  DEBOUNCE_MS: 250,
  MAX_SEARCH_RESULTS: 50,
  SEARCH_PREVIEW_LENGTH: 500,
  AI: {
    DEFAULT_MODEL: "google/gemini-3.1-flash",
    DEFAULT_TARGET_LANG: "tr",
    CHUNK_SIZE: 3000,
    AVAILABLE_LANGUAGES: [
      { code: "tr", name: "Türkçe" },
      { code: "en", name: "English" },
      { code: "de", name: "Deutsch" },
      { code: "fr", name: "Français" },
      { code: "es", name: "Español" },
      { code: "ja", name: "日本語" },
      { code: "ko", name: "한국어" },
      { code: "zh", name: "中文" },
      { code: "ar", name: "العربية" },
      { code: "ru", name: "Русский" },
    ],
    OPENROUTER_URL: "https://openrouter.ai/api/v1/chat/completions",
    SUMMARY_FORMATS: [
      { id: "structured", name: "Yapılandırılmış", description: "Ana konu, önemli noktalar ve sonuç" },
      { id: "bullets", name: "Madde İşaretli", description: "Sadece madde işaretli liste" },
      { id: "paragraph", name: "Paragraf", description: "Akıcı paragraf formatında" },
      { id: "tldr", name: "TL;DR", description: "2-3 cümlelik ultra kısa özet" },
    ] as const,
    SUMMARY_TONES: [
      { id: "neutral", name: "Nötr" },
      { id: "simple", name: "Basit / Sade" },
      { id: "technical", name: "Teknik" },
      { id: "academic", name: "Akademik" },
      { id: "casual", name: "Günlük / Samimi" },
    ] as const,
    SUMMARY_LENGTHS: [
      { id: "short", name: "Kısa" },
      { id: "medium", name: "Orta" },
      { id: "long", name: "Detaylı" },
    ] as const,
  },
  FUSE_OPTIONS: {
    keys: [
      { name: "title", weight: 0.35 },
      { name: "channel", weight: 0.25 },
      { name: "tags", weight: 0.25 },
      { name: "searchableTranscript", weight: 0.15 },
    ],
    threshold: 0.4,
    distance: 100,
    ignoreLocation: true,
    useExtendedSearch: true,
    minMatchCharLength: 2,
    includeScore: true,
    includeMatches: true,
    findAllMatches: false,
    shouldSort: true,
  },
};
