export const CONFIG = {
  DB_NAME: "YouTubeTranscriptPro",
  DB_VERSION: 2,
  STORE_NAME: "transcripts",
  DEBOUNCE_MS: 250,
  MAX_SEARCH_RESULTS: 50,
  SEARCH_PREVIEW_LENGTH: 500,
  AI: {
    DEFAULT_MODEL: "google/gemini-3.1-flash",
    DEFAULT_TARGET_LANG: "tr",
    CHUNK_SIZE: 3000,
    AVAILABLE_LANGUAGES: [
      { code: "tr", name: "Türkçe" },
      { code: "en", name: "English" },
      { code: "de", name: "Deutsch" },
      { code: "fr", name: "Français" },
      { code: "es", name: "Español" },
      { code: "ja", name: "日本語" },
      { code: "ko", name: "한국어" },
      { code: "zh", name: "中文" },
      { code: "ar", name: "العربية" },
      { code: "ru", name: "Русский" },
    ],
    OPENROUTER_URL: "https://openrouter.ai/api/v1/chat/completions",
  },
  FUSE_OPTIONS: {
    keys: [
      { name: "title", weight: 0.35 },
      { name: "channel", weight: 0.25 },
      { name: "tags", weight: 0.25 },
      { name: "searchableTranscript", weight: 0.15 },
    ],
    threshold: 0.4,
    distance: 100,
    ignoreLocation: true,
    useExtendedSearch: true,
    minMatchCharLength: 2,
    includeScore: true,
    includeMatches: true,
    findAllMatches: false,
    shouldSort: true,
  },
};
